# Auto-generated by QA Agent — do not edit manually
# Requirement: REQ-001 — System shall support user registration and login with email/password authentication
# Feature Types: ui, api, security
# Generated: 2024-01-24

import os
import time
import pytest
import httpx
from playwright.sync_api import sync_playwright, expect

BASE_URL = os.getenv("TARGET_BASE_URL", "http://127.0.0.1:8001")

# ── Fixtures ────────────────────────────────────────
@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE_URL, timeout=30.0) as c:
        yield c

@pytest.fixture(scope="function")
def browser_page():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        yield page
        if pytest.current_test().failed:
            page.screenshot(path=f"screenshots/{pytest.current_test().name}.png")
        context.close()
        browser.close()

# ── API Test Class ─────────────────────────────────
class TestREQ001API:

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_001_01_positive_register_success(self, client):
        """
        TC-REQ-001-01 [positive]
        User successfully registers with valid email and password
        """
        # Arrange
        payload = {
            "email": "testuser@example.com",
            "password": "SecurePass123!"
        }
        
        # Act
        response = client.post("/auth/register", json=payload)
        
        # Assert
        assert response.status_code == 201
        data = response.json()
        assert "user_id" in data
        assert "message" in data

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_001_02_positive_login_success(self, client):
        """
        TC-REQ-001-02 [positive]
        User successfully logs in with valid registered credentials
        """
        # Arrange
        payload = {
            "email": "testuser@example.com",
            "password": "SecurePass123!"
        }
        
        # Act
        response = client.post("/auth/login", json=payload)
        
        # Assert
        assert response.status_code == 200
        data = response.json()
        assert "token" in data
        assert response.headers.get("Authorization").startswith("Bearer ")

    @pytest.mark.negative
    @pytest.mark.api
    @pytest.mark.parametrize("email,password", [
        ("testuser@example.com", "WrongPassword123!"),
        ("nonexistent@example.com", "SomePass123!")
    ])
    def test_TC_REQ_001_04_05_negative_login_fails(self, client, email, password):
        """
        TC-REQ-001-04/05 [negative]
        Login fails with incorrect password or non-existent email
        """
        # Arrange
        payload = {"email": email, "password": password}
        
        # Act
        response = client.post("/auth/login", json=payload)
        
        # Assert
        assert response.status_code == 401
        data = response.json()
        assert data["message"] == "Invalid credentials"

    @pytest.mark.edge
    @pytest.mark.api
    def test_TC_REQ_001_06_edge_account_lockout(self, client):
        """
        TC-REQ-001-06 [edge]
        Account is locked after 5 consecutive failed login attempts
        """
        # Arrange
        email = "testuser@example.com"
        wrong_payload = {"email": email, "password": "WrongPass123!"}
        correct_payload = {"email": email, "password": "SecurePass123!"}
        
        # Act - Make 5 failed attempts
        for _ in range(5):
            response = client.post("/auth/login", json=wrong_payload)
            assert response.status_code == 401
        
        # Try correct credentials immediately after
        response = client.post("/auth/login", json=correct_payload)
        
        # Assert - Account should be locked
        assert response.status_code == 423
        assert response.json()["message"] == "Account locked"
        
        # Note: In real test, we'd mock time instead of actually waiting
        pytest.skip("Skipping 15-minute wait - in real test would mock time")

# ── UI Test Class ──────────────────────────────────
class TestREQ001UI:

    @pytest.mark.positive
    @pytest.mark.ui
    def test_TC_REQ_001_01_positive_register_ui(self, browser_page):
        """
        TC-REQ-001-01 [positive]
        User successfully registers through UI form
        """
        page = browser_page
        
        # Arrange
        page.goto(f"{BASE_URL}/auth/register")
        page.wait_for_load_state("networkidle")
        
        # Act
        page.get_by_label("Email").fill("testuser@example.com")
        page.get_by_label("Password").fill("SecurePass123!")
        page.get_by_role("button", name="Register").click()
        
        # Assert
        success_message = page.get_by_text("Registration successful")
        expect(success_message).to_be_visible()

    @pytest.mark.positive
    @pytest.mark.ui
    def test_TC_REQ_001_02_positive_login_ui(self, browser_page):
        """
        TC-REQ-001-02 [positive]
        User successfully logs in through UI form
        """
        page = browser_page
        
        # Arrange
        page.goto(f"{BASE_URL}/auth/login")
        page.wait_for_load_state("networkidle")
        
        # Act
        page.get_by_label("Email").fill("testuser@example.com")
        page.get_by_label("Password").fill("SecurePass123!")
        page.get_by_role("button", name="Login").click()
        
        # Assert
        expect(page.get_by_text("Welcome back")).to_be_visible()

    @pytest.mark.positive
    @pytest.mark.ui
    def test_TC_REQ_001_03_positive_google_oauth(self, browser_page):
        """
        TC-REQ-001-03 [positive]
        User successfully authenticates using Google OAuth2
        """
        page = browser_page
        
        # Arrange
        page.goto(f"{BASE_URL}/auth/login")
        page.wait_for_load_state("networkidle")
        
        # Act
        page.get_by_role("button", name="Sign in with Google").click()
        
        # Note: Full OAuth2 flow testing would require mock Google auth server
        pytest.skip("OAuth2 flow test requires mock Google auth server")
