# Auto-generated by QA Agent — do not edit manually
# Requirement: REQ-002 — System shall display products in a paginated list with search and filtering
# Feature Types: ui, api
# Generated: 2024-01-22

import os
import pytest
import httpx
from playwright.sync_api import sync_playwright, expect
from locust import HttpUser, task, between
from typing import Dict, List

BASE_URL = os.getenv("TARGET_BASE_URL", "http://127.0.0.1:8001")

# ── Fixtures ────────────────────────────────────────
@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE_URL, timeout=30.0) as c:
        yield c

@pytest.fixture(scope="module")
def browser_page():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        page.goto(BASE_URL)
        yield page
        browser.close()

# ── API Tests ────────────────────────────────────────
class TestREQ002ProductAPI:

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_002_01_positive_paginated_listing(self, client):
        """
        TC-REQ-002-01 [positive]
        Product listing returns paginated results with all required fields
        """
        # Arrange
        params = {"page": 1, "per_page": 10}
        required_fields = ["id", "name", "description", "price", "stock_quantity", "category"]

        # Act
        response = client.get("/products", params=params)

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert "products" in data
        assert len(data["products"]) <= 10
        
        # Verify all required fields are present
        for product in data["products"]:
            for field in required_fields:
                assert field in product, f"Field {field} missing from product"

        # Verify response time
        assert response.elapsed.total_seconds() < 0.2

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_002_02_positive_search_by_name(self, client):
        """
        TC-REQ-002-02 [positive]
        Product search by name returns matching results
        """
        # Arrange
        search_term = "laptop"
        params = {"search": search_term, "page": 1, "per_page": 10}

        # Act
        response = client.get("/products", params=params)

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert "products" in data
        
        for product in data["products"]:
            search_match = (
                search_term.lower() in product["name"].lower() or
                search_term.lower() in product["description"].lower()
            )
            assert search_match, f"Product {product['id']} does not match search term"

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_002_03_positive_out_of_stock_marking(self, client):
        """
        TC-REQ-002-03 [positive]
        Out-of-stock products are correctly marked in listing
        """
        # Arrange
        params = {"page": 1, "per_page": 50}

        # Act
        response = client.get("/products", params=params)

        # Assert
        assert response.status_code == 200
        data = response.json()
        
        # Check out of stock products
        out_of_stock_products = [
            p for p in data["products"] if p["stock_quantity"] == 0
        ]
        for product in out_of_stock_products:
            assert product["status"] == "Out of Stock"

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_002_04_negative_no_search_results(self, client):
        """
        TC-REQ-002-04 [negative]
        Product search with no matching results returns empty list
        """
        # Arrange
        params = {"search": "nonexistentproduct12345", "page": 1, "per_page": 10}

        # Act
        response = client.get("/products", params=params)

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["products"] == []
        assert data["total_count"] == 0

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_002_05_negative_invalid_category(self, client):
        """
        TC-REQ-002-05 [negative]
        Product filtering by invalid category returns empty list
        """
        # Arrange
        params = {"category": "invalidcategory123", "page": 1, "per_page": 10}

        # Act
        response = client.get("/products", params=params)

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["products"] == []

# ── Performance Test ────────────────────────────────
class ProductListingUser(HttpUser):
    wait_time = between(1, 2)
    host = BASE_URL

    @task
    def get_products(self):
        with self.client.get(
            "/products",
            params={"page": 1, "per_page": 10},
            catch_response=True
        ) as response:
            if response.elapsed.total_seconds() > 0.2:
                response.failure("Response took too long")
            elif response.status_code != 200:
                response.failure("Wrong status code")
            else:
                response.success()

@pytest.mark.performance
@pytest.mark.edge
def test_TC_REQ_002_06_edge_concurrent_users():
    """
    TC-REQ-002-06 [edge]
    Product listing API responds within 200ms under 1000 concurrent users
    """
    # Note: This test should be run using locust CLI with:
    # locust -f test_REQ_002_product_listing.py --headless -u 1000 -r 100 --run-time 30s
    pytest.skip("Performance test should be run via Locust CLI")

# ── UI Tests ────────────────────────────────────────
class TestREQ002ProductUI:

    @pytest.mark.ui
    @pytest.mark.positive
    def test_product_listing_display(self, browser_page):
        """
        Verify product listing is displayed correctly in UI
        """
        # Arrange
        page = browser_page
        page.goto(f"{BASE_URL}/products")
        page.wait_for_load_state("networkidle")

        # Act & Assert
        product_grid = page.locator(".product-grid")
        expect(product_grid).to_be_visible()
        
        # Check pagination
        expect(page.get_by_role("navigation", name="pagination")).to_be_visible()
        
        # Check product cards
        products = page.locator(".product-card").all()
        for product in products:
            expect(product.locator(".product-name")).to_be_visible()
            expect(product.locator(".product-price")).to_be_visible()
            
            # Check if out of stock products are marked
            stock_status = product.locator(".stock-status")
            if stock_status.text_content() == "Out of Stock":
                expect(stock_status).to_have_class("out-of-stock")

        page.screenshot(path="screenshots/product_listing.png")
