# Auto-generated by QA Agent — do not edit manually
# Requirement: REQ-003 — Authenticated users can manage their shopping cart
# Feature Types: ui, api, security
# Generated: 2024-01-24

import os
import pytest
import httpx
from playwright.sync_api import expect

BASE_URL = os.getenv("TARGET_BASE_URL", "http://127.0.0.1:8001")

# ── Fixtures ──────────────────────────────────────────
@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE_URL) as c:
        yield c

@pytest.fixture(scope="function")
async def auth_token(client):
    """Get JWT token for authenticated requests"""
    response = client.post("/auth/login", json={
        "email": os.getenv("TEST_USER_EMAIL", "test@example.com"),
        "password": os.getenv("TEST_USER_PASSWORD", "testpass123")
    })
    assert response.status_code == 200
    return response.json()["access_token"]

@pytest.fixture(scope="function")
def auth_headers(auth_token):
    return {"Authorization": f"Bearer {auth_token}"}


# ── API Tests ────────────────────────────────────────
class TestREQ003CartAPI:

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_003_01_positive_add_item_to_cart(self, client, auth_headers):
        """
        TC-REQ-003-01 [positive]
        Authenticated user successfully adds item to cart with valid product_id and quantity
        """
        # Arrange
        payload = {"product_id": 5, "quantity": 2}

        # Act
        response = client.post("/cart/items", json=payload, headers=auth_headers)

        # Assert
        assert response.status_code == 201
        data = response.json()
        assert "items" in data
        assert "total_price" in data
        added_item = next((item for item in data["items"] if item["product_id"] == 5), None)
        assert added_item is not None
        assert added_item["quantity"] == 2

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_003_02_positive_multiple_items_total(self, client, auth_headers):
        """
        TC-REQ-003-02 [positive]
        Multiple items can be added to cart and total updates correctly
        """
        # Arrange
        items = [
            {"product_id": 5, "quantity": 2},  # $10 each
            {"product_id": 7, "quantity": 1}   # $15 each
        ]

        # Act
        for item in items:
            response = client.post("/cart/items", json=item, headers=auth_headers)
            assert response.status_code == 201

        cart_response = client.get("/cart", headers=auth_headers)

        # Assert
        assert cart_response.status_code == 200
        cart_data = cart_response.json()
        assert len(cart_data["items"]) == 2
        assert cart_data["total_price"] == 35  # (10*2) + (15*1)

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_003_03_positive_remove_cart_item(self, client, auth_headers):
        """
        TC-REQ-003-03 [positive]
        User successfully removes item from cart
        """
        # Arrange - First add an item
        add_response = client.post("/cart/items", 
            json={"product_id": 5, "quantity": 1},
            headers=auth_headers
        )
        cart_item_id = add_response.json()["items"][0]["cart_item_id"]

        # Act
        delete_response = client.delete(
            f"/cart/items/{cart_item_id}",
            headers=auth_headers
        )

        # Assert
        assert delete_response.status_code == 204

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_003_04_positive_empty_cart_state(self, client, auth_headers):
        """
        TC-REQ-003-04 [positive]
        Empty cart returns correct empty state
        """
        # Arrange - Clear cart by removing all items
        cart = client.get("/cart", headers=auth_headers).json()
        for item in cart.get("items", []):
            client.delete(f"/cart/items/{item['cart_item_id']}", headers=auth_headers)

        # Act
        response = client.get("/cart", headers=auth_headers)

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["items"] == []
        assert data["total_price"] == 0

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_003_06_negative_out_of_stock_item(self, client, auth_headers):
        """
        TC-REQ-003-06 [negative]
        Adding out-of-stock item to cart returns error
        """
        # Arrange
        payload = {"product_id": 99, "quantity": 1}  # Assuming product 99 is out of stock

        # Act
        response = client.post("/cart/items", json=payload, headers=auth_headers)

        # Assert
        assert response.status_code == 400
        assert "insufficient stock" in response.json()["detail"].lower()

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_003_07_negative_quantity_exceeds_stock(self, client, auth_headers):
        """
        TC-REQ-003-07 [negative]
        Adding quantity exceeding stock returns error
        """
        # Arrange
        payload = {"product_id": 5, "quantity": 999}

        # Act
        response = client.post("/cart/items", json=payload, headers=auth_headers)

        # Assert
        assert response.status_code == 400
        assert "exceeds available stock" in response.json()["detail"].lower()

    @pytest.mark.negative
    @pytest.mark.security
    def test_TC_REQ_003_08_negative_unauthorized_cart_access(self, client):
        """
        TC-REQ-003-08 [negative]
        Unauthenticated request to add item to cart returns 401
        """
        # Arrange
        payload = {"product_id": 5, "quantity": 2}

        # Act
        response = client.post("/cart/items", json=payload)

        # Assert
        assert response.status_code == 401

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_003_09_negative_delete_nonexistent_item(self, client, auth_headers):
        """
        TC-REQ-003-09 [negative]
        Deleting non-existent cart item returns 404
        """
        # Act
        response = client.delete("/cart/items/99999", headers=auth_headers)

        # Assert
        assert response.status_code == 404


# ── UI Tests ─────────────────────────────────────────
class TestREQ003CartUI:

    @pytest.mark.positive
    @pytest.mark.ui
    def test_TC_REQ_003_05_positive_cart_persistence(self, page):
        """
        TC-REQ-003-05 [positive]
        Cart persists across multiple sessions for same user
        """
        # Arrange - First login and add item
        page.goto(f"{BASE_URL}/login")
        page.wait_for_load_state("networkidle")
        
        page.get_by_label("Email").fill(os.getenv("TEST_USER_EMAIL", "test@example.com"))
        page.get_by_label("Password").fill(os.getenv("TEST_USER_PASSWORD", "testpass123"))
        page.get_by_role("button", name="Login").click()
        page.wait_for_load_state("networkidle")

        # Add item to cart
        page.goto(f"{BASE_URL}/products/5")
        page.wait_for_load_state("networkidle")
        page.get_by_role("spinbutton").fill("2")
        page.get_by_role("button", name="Add to Cart").click()

        # Logout
        page.get_by_role("button", name="Logout").click()
        page.wait_for_load_state("networkidle")

        # Act - Login again and check cart
        page.get_by_label("Email").fill(os.getenv("TEST_USER_EMAIL"))
        page.get_by_label("Password").fill(os.getenv("TEST_USER_PASSWORD"))
        page.get_by_role("button", name="Login").click()
        page.wait_for_load_state("networkidle")

        # Navigate to cart
        page.get_by_role("link", name="Cart").click()
        page.wait_for_load_state("networkidle")

        # Assert
        cart_items = page.locator(".cart-item")
        expect(cart_items).to_have_count(1)
        product_name = page.locator(".cart-item:first-child .product-name")
        expect(product_name).to_be_visible()

        # Cleanup - Remove item from cart
        page.get_by_role("button", name="Remove").click()
        page.wait_for_load_state("networkidle")

    @pytest.mark.edge
    @pytest.mark.ui
    def test_TC_REQ_003_10_edge_price_change_updates_total(self, page):
        """
        TC-REQ-003-10 [edge]
        Cart total updates when product price changes after item added
        """
        # Login and add item at original price
        page.goto(f"{BASE_URL}/login")
        page.wait_for_load_state("networkidle")
        page.get_by_label("Email").fill(os.getenv("TEST_USER_EMAIL"))
        page.get_by_label("Password").fill(os.getenv("TEST_USER_PASSWORD"))
        page.get_by_role("button", name="Login").click()
        page.wait_for_load_state("networkidle")

        # Add product to cart
        page.goto(f"{BASE_URL}/products/5")
        page.wait_for_load_state("networkidle")
        page.get_by_role("spinbutton").fill("2")
        page.get_by_role("button", name="Add to Cart").click()

        # Get initial total
        initial_total = page.locator(".cart-total").inner_text()
        assert "$20" in initial_total  # $10 * 2

        # Simulate price update (would normally be done by admin in separate session)
        # For test purposes, we'll trigger a price refresh
        page.reload()
        page.wait_for_load_state("networkidle")

        # Assert new total reflects updated price
        new_total = page.locator(".cart-total").inner_text()
        assert "$30" in new_total  # $15 * 2

        # Cleanup
        page.get_by_role("button", name="Remove").click()
        page.wait_for_load_state("networkidle")
