# Auto-generated by QA Agent — do not edit manually
# Requirement: REQ-005 — System security controls and ETL pipeline validation
# Feature Types: api, security, etl
# Generated: 2024-01-24

import os
import pytest
import httpx
from databricks import sql


BASE_URL = os.getenv("TARGET_BASE_URL", "http://127.0.0.1:8001")
DATABRICKS_HOST = os.getenv("DATABRICKS_SERVER_HOSTNAME")
DATABRICKS_PATH = os.getenv("DATABRICKS_HTTP_PATH")
DATABRICKS_TOKEN = os.getenv("DATABRICKS_TOKEN")


# ── Fixtures ──────────────────────────────────────────
@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE_URL, timeout=30.0) as c:
        yield c


@pytest.fixture(scope="module")
def auth_token(client):
    """Get JWT token for authenticated requests"""
    response = client.post("/auth/login", json={
        "email": os.getenv("TEST_USER_EMAIL", "test@example.com"),
        "password": os.getenv("TEST_USER_PASSWORD", "TestPass123!")
    })
    assert response.status_code == 200
    return response.json()["token"]


@pytest.fixture(scope="module")
def db_connection():
    conn = sql.connect(
        server_hostname=DATABRICKS_HOST,
        http_path=DATABRICKS_PATH,
        access_token=DATABRICKS_TOKEN
    )
    yield conn
    conn.close()


@pytest.fixture(scope="module")
def cursor(db_connection):
    cur = db_connection.cursor()
    yield cur
    cur.close()


# ── API Security Tests ─────────────────────────────────
class TestREQ005APISecurity:

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_005_01_positive_protected_endpoints_require_jwt(self, client, auth_token):
        """
        TC-REQ-005-01 [positive]
        Protected API endpoints require valid JWT authentication
        """
        # Arrange
        headers = {"Authorization": f"Bearer {auth_token}"}
        # Act
        response = client.get("/cart", headers=headers)
        # Assert
        assert response.status_code == 200
        assert "items" in response.json()

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_005_02_positive_public_endpoints_no_auth(self, client):
        """
        TC-REQ-005-02 [positive]
        Public endpoints /auth and /products do not require authentication
        """
        # Act & Assert - Products endpoint
        products_response = client.get("/products")
        assert products_response.status_code == 200
        
        # Act & Assert - Auth endpoint
        auth_response = client.post("/auth/login", json={
            "email": "invalid@example.com",
            "password": "wrong"
        })
        assert auth_response.status_code == 400  # Invalid credentials but endpoint accessible

    @pytest.mark.positive
    @pytest.mark.security
    def test_TC_REQ_005_03_positive_password_bcrypt_hashing(self, client, cursor):
        """
        TC-REQ-005-03 [positive]
        User passwords are hashed using bcrypt before storage
        """
        # Arrange
        test_email = f"test_{os.urandom(4).hex()}@example.com"
        test_password = "TestPass123!"
        
        # Act - Register new user
        register_response = client.post("/auth/register", json={
            "email": test_email,
            "password": test_password
        })
        assert register_response.status_code == 201
        
        # Assert - Check password hash in database
        cursor.execute(
            "SELECT password_hash FROM users WHERE email = %s",
            (test_email,)
        )
        result = cursor.fetchone()
        stored_hash = result[0]
        assert stored_hash != test_password
        assert stored_hash.startswith("$2")  # bcrypt hash prefix

    @pytest.mark.negative
    @pytest.mark.security
    def test_TC_REQ_005_05_negative_protected_endpoints_no_token(self, client):
        """
        TC-REQ-005-05 [negative]
        Protected endpoints return 401 without valid JWT token
        """
        # Act & Assert
        endpoints = ["/cart", "/orders"]
        for endpoint in endpoints:
            response = client.get(endpoint)
            assert response.status_code == 401
            assert "token" in response.json()["detail"].lower()

    @pytest.mark.negative
    @pytest.mark.security
    def test_TC_REQ_005_07_negative_sql_injection_prevention(self, client):
        """
        TC-REQ-005-07 [negative]
        SQL injection attack is prevented
        """
        # Arrange
        sql_injection_attempts = [
            "'; DROP TABLE products; --",
            "admin' OR '1'='1",
            "\" OR \"1\"=\"1",
            "1 UNION SELECT * FROM users--"
        ]
        
        # Act & Assert
        for payload in sql_injection_attempts:
            # Test search endpoint
            search_response = client.get("/products", params={"search": payload})
            assert search_response.status_code in [200, 400]
            assert "error" not in search_response.text.lower()
            
            # Test login endpoint
            login_response = client.post("/auth/login", json={
                "email": payload,
                "password": payload
            })
            assert login_response.status_code == 400
            assert "sql" not in login_response.text.lower()

    @pytest.mark.negative
    @pytest.mark.security
    def test_TC_REQ_005_08_negative_xss_prevention(self, client):
        """
        TC-REQ-005-08 [negative]
        XSS attack is prevented in product search
        """
        # Arrange
        xss_payload = "<script>alert('XSS')</script>"
        
        # Act
        response = client.get("/products", params={"search": xss_payload})
        
        # Assert
        assert response.status_code == 200
        content = response.text
        assert xss_payload not in content
        assert "&lt;script&gt;" in content or "<script" not in content


# ── ETL Pipeline Tests ─────────────────────────────────
class TestREQ005ETLPipeline:

    @pytest.mark.positive
    @pytest.mark.etl
    def test_TC_REQ_005_04_positive_order_etl_pipeline_flow(self, client, auth_token, cursor):
        """
        TC-REQ-005-04 [positive]
        Order data flows through Bronze-Silver-Gold ETL pipeline
        """
        # Arrange - Place test order
        headers = {"Authorization": f"Bearer {auth_token}"}
        order_response = client.post("/orders", json={
            "items": [{"product_id": "PROD-001", "quantity": 1}]
        }, headers=headers)
        assert order_response.status_code == 201
        order_id = order_response.json()["order_id"]
        
        # Assert - Check Bronze layer (raw events)
        cursor.execute(
            "SELECT * FROM bronze.order_events WHERE order_id = %s",
            (order_id,)
        )
        bronze_record = cursor.fetchone()
        assert bronze_record is not None
        
        # Assert - Check Silver layer (validated)
        cursor.execute(
            "SELECT * FROM silver.orders WHERE order_id = %s",
            (order_id,)
        )
        silver_record = cursor.fetchone()
        assert silver_record is not None
        assert silver_record["validation_status"] == "PASSED"
        
        # Assert - Check Gold layer (aggregated)
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM gold.daily_revenue 
            WHERE date = CURRENT_DATE 
            AND revenue > 0
            """
        )
        assert cursor.fetchone()[0] > 0

    @pytest.mark.edge
    @pytest.mark.etl
    def test_TC_REQ_005_09_edge_silver_rejects_invalid_orders(self, cursor):
        """
        TC-REQ-005-09 [edge]
        Silver layer rejects orders with missing required fields during validation
        """
        # Arrange - Insert invalid order into Bronze
        test_order_id = f"TEST-{os.urandom(4).hex()}"
        cursor.execute(
            """
            INSERT INTO bronze.order_events (
                order_id, event_type, event_data
            ) VALUES (
                %s, 'order_created', '{"items": [{"product_id": "PROD-001"}]}'
            )
            """,
            (test_order_id,)
        )
        
        # Act - Trigger ETL (normally automated, using manual trigger for test)
        cursor.execute("CALL silver.process_new_orders()")
        
        # Assert - Check Silver validation
        cursor.execute(
            "SELECT COUNT(*) FROM silver.orders WHERE order_id = %s",
            (test_order_id,)
        )
        assert cursor.fetchone()[0] == 0
        
        # Assert - Check error logs
        cursor.execute(
            "SELECT * FROM silver.validation_errors WHERE order_id = %s",
            (test_order_id,)
        )
        error = cursor.fetchone()
        assert error is not None
        assert "missing required field" in error["error_message"].lower()

    @pytest.mark.edge
    @pytest.mark.etl
    def test_TC_REQ_005_10_edge_etl_handles_duplicates(self, cursor):
        """
        TC-REQ-005-10 [edge]
        ETL pipeline handles duplicate orders correctly
        """
        # Arrange - Insert duplicate order events
        test_order_id = f"TEST-{os.urandom(4).hex()}"
        event_data = """
        {
            "order_id": "%s",
            "customer_id": "CUST-001",
            "items": [{"product_id": "PROD-001", "quantity": 1}],
            "total": 29.99
        }
        """ % test_order_id
        
        # Act - Insert same order twice
        for _ in range(2):
            cursor.execute(
                """
                INSERT INTO bronze.order_events (
                    order_id, event_type, event_data
                ) VALUES (%s, 'order_created', %s)
                """,
                (test_order_id, event_data)
            )
        
        # Trigger ETL
        cursor.execute("CALL silver.process_new_orders()")
        
        # Assert - Check Silver for single record
        cursor.execute(
            "SELECT COUNT(*) FROM silver.orders WHERE order_id = %s",
            (test_order_id,)
        )
        assert cursor.fetchone()[0] == 1
        
        # Assert - Check Gold aggregation
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM gold.daily_revenue 
            WHERE order_ids ? %s
            """,
            (test_order_id,)
        )
        assert cursor.fetchone()[0] == 1