# Auto-generated by QA Agent — do not edit manually
# Requirement: REQ-004 — Users can place orders from their cart with payment processing
# Feature Types: ui, api, performance
# Generated: 2024-01-24

import os
import time
import pytest
import httpx
from playwright.sync_api import sync_playwright, expect
from locust import HttpUser, task, between

BASE_URL = os.getenv('TARGET_BASE_URL', 'http://127.0.0.1:8001')
TEST_USER = os.getenv('TEST_USER_EMAIL', 'test@example.com')
TEST_PASS = os.getenv('TEST_USER_PASSWORD', 'testpass123')

# ── Fixtures ──────────────────────────────────────────
@pytest.fixture(scope='module')
def client():
    with httpx.Client(base_url=BASE_URL, timeout=30.0) as c:
        yield c

@pytest.fixture(scope='module')
def auth_headers(client):
    response = client.post('/login', json={
        'email': TEST_USER,
        'password': TEST_PASS
    })
    token = response.json()['token']
    return {'Authorization': f'Bearer {token}'}

@pytest.fixture(scope='module')
def browser_page():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        yield page
        browser.close()

# ── API Tests ───────────────────────────────────────────
class TestREQ004API:
    
    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_004_01_positive_successful_order_placement(self, client, auth_headers):
        """
        TC-REQ-004-01 [positive]
        User successfully places order with valid payment
        """
        # Arrange
        client.post('/cart/items', json={
            'product_id': 5,
            'quantity': 2
        }, headers=auth_headers)
        
        # Act
        response = client.post('/orders', json={
            'payment_token': 'valid_token_123'
        }, headers=auth_headers)
        
        # Assert
        assert response.status_code == 201
        data = response.json()
        assert 'order_id' in data
        assert data['status'] == 'confirmed'
        assert data['total'] == 20.0

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_004_02_positive_stock_decremented(self, client, auth_headers):
        """
        TC-REQ-004-02 [positive]
        Stock is decremented after successful order placement
        """
        # Arrange - Get initial stock
        initial_resp = client.get('/products/5')
        initial_stock = initial_resp.json()['stock']
        
        # Add to cart and place order
        client.post('/cart/items', json={
            'product_id': 5,
            'quantity': 3
        }, headers=auth_headers)
        
        # Act
        client.post('/orders', json={
            'payment_token': 'valid_token_123'
        }, headers=auth_headers)
        
        # Assert
        final_resp = client.get('/products/5')
        final_stock = final_resp.json()['stock']
        assert final_stock == initial_stock - 3

    @pytest.mark.positive
    @pytest.mark.api
    def test_TC_REQ_004_03_positive_cart_cleared(self, client, auth_headers):
        """
        TC-REQ-004-03 [positive]
        Cart is cleared after successful order placement
        """
        # Arrange - Add items to cart
        client.post('/cart/items', json={
            'product_id': 5,
            'quantity': 2
        }, headers=auth_headers)
        
        # Act - Place order
        client.post('/orders', json={
            'payment_token': 'valid_token_123'
        }, headers=auth_headers)
        
        # Assert - Check cart is empty
        cart_response = client.get('/cart', headers=auth_headers)
        cart_data = cart_response.json()
        assert cart_data['items'] == []
        assert cart_data['total_price'] == 0

    @pytest.mark.negative
    @pytest.mark.api
    def test_TC_REQ_004_05_negative_empty_cart(self, client, auth_headers):
        """
        TC-REQ-004-05 [negative]
        Order placement with empty cart returns 400
        """
        # Arrange - Ensure cart is empty
        client.delete('/cart', headers=auth_headers)
        
        # Act
        response = client.post('/orders', json={
            'payment_token': 'valid_token_123'
        }, headers=auth_headers)
        
        # Assert
        assert response.status_code == 400
        assert response.json()['message'] == 'Cart is empty'

    @pytest.mark.negative
    @pytest.mark.api
    @pytest.mark.parametrize('payment_token,expected_message', [
        ('invalid_token_xyz', 'Payment failed'),
        ('declined_card_0002', 'Card declined')
    ])
    def test_TC_REQ_004_06_07_negative_payment_failures(
        self, client, auth_headers, payment_token, expected_message
    ):
        """
        TC-REQ-004-06/07 [negative]
        Order placement with failed/declined payment returns 402
        """
        # Arrange
        client.post('/cart/items', json={
            'product_id': 5,
            'quantity': 1
        }, headers=auth_headers)
        
        # Act
        response = client.post('/orders', json={
            'payment_token': payment_token
        }, headers=auth_headers)
        
        # Assert
        assert response.status_code == 402
        assert expected_message in response.json()['message']

    @pytest.mark.edge
    @pytest.mark.api
    def test_TC_REQ_004_08_edge_payment_timeout(self, client, auth_headers):
        """
        TC-REQ-004-08 [edge]
        Order placement with payment timeout after 30 seconds
        """
        # Arrange
        client.post('/cart/items', json={
            'product_id': 5,
            'quantity': 1
        }, headers=auth_headers)
        
        # Act & Assert
        with pytest.raises(httpx.TimeoutException):
            client.post(
                '/orders',
                json={'payment_token': 'timeout_token'},
                headers=auth_headers,
                timeout=1.0
            )

        # Verify cart still contains items
        cart_response = client.get('/cart', headers=auth_headers)
        assert len(cart_response.json()['items']) > 0

# ── UI Tests ────────────────────────────────────────────
class TestREQ004UI:
    
    @pytest.mark.positive
    @pytest.mark.ui
    def test_TC_REQ_004_04_positive_email_confirmation(self, browser_page):
        """
        TC-REQ-004-04 [positive]
        Order confirmation email is sent within 60 seconds
        """
        # Arrange - Log in
        browser_page.goto(f'{BASE_URL}/login')
        browser_page.get_by_label('Email').fill(TEST_USER)
        browser_page.get_by_label('Password').fill(TEST_PASS)
        browser_page.get_by_role('button', name='Log in').click()
        browser_page.wait_for_load_state('networkidle')
        
        # Add item to cart
        browser_page.goto(f'{BASE_URL}/products/5')
        browser_page.get_by_role('button', name='Add to Cart').click()
        browser_page.wait_for_load_state('networkidle')
        
        # Act - Place order
        browser_page.goto(f'{BASE_URL}/checkout')
        browser_page.get_by_role('button', name='Place Order').click()
        order_time = time.time()
        
        # Assert - Check email received
        browser_page.goto(f'{BASE_URL}/email-inbox')
        email_element = browser_page.get_by_text('Order Confirmation').first
        expect(email_element).to_be_visible(timeout=60000)
        
        delivery_time = time.time()
        assert delivery_time - order_time <= 60
        
        # Take screenshot on success
        browser_page.screenshot(
            path='screenshots/test_email_confirmation_success.png'
        )

# ── Performance Tests ─────────────────────────────────────
class OrderPlacementUser(HttpUser):
    wait_time = between(1, 3)
    
    def on_start(self):
        # Log in and get token
        response = self.client.post('/login', json={
            'email': TEST_USER,
            'password': TEST_PASS
        })
        self.token = response.json()['token']
        self.headers = {'Authorization': f'Bearer {self.token}'}
    
    @task
    def test_TC_REQ_004_09_edge_concurrent_orders(self):
        """
        TC-REQ-004-09 [edge]
        Checkout API handles 500 concurrent order requests
        """
        # Add item to cart
        self.client.post(
            '/cart/items',
            json={'product_id': 5, 'quantity': 1},
            headers=self.headers
        )
        
        # Place order
        start_time = time.time()
        response = self.client.post(
            '/orders',
            json={'payment_token': 'valid_token_123'},
            headers=self.headers
        )
        
        # Record metrics
        request_time = time.time() - start_time
        if response.status_code == 201:
            self.environment.events.request_success.fire(
                request_type='POST',
                name='/orders',
                response_time=request_time,
                response_length=len(response.content)
            )
        else:
            self.environment.events.request_failure.fire(
                request_type='POST',
                name='/orders',
                response_time=request_time,
                exception=Exception(f'Status {response.status_code}')
            )
